---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: spring-helm
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: networking.istio.io
    jsonPointers:
    - /spec/http
    kind: VirtualService
  project: default
  source:
    helm:
      values: |
        image:
          tag: "db8c789"
        service:
          targetPort: 8080
        ingress:
          enabled: false
          host: spring-helm.35.197.205.55.xip.io
        istio:
          enabled: true
        hpa: true
        rollout:
          enabled: true
      version: v3
    path: helm
    repoURL: https://github.com/sguisado/spring-helm
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
