apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: production
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/sguisado/codefresh-production
    targetRevision: HEAD